[package]
name = "shade-dsl"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "3.17.0"
ctx2d-utils = { version = "0.1.0", path = "../ctx2d-utils" }
derive-where = "1.3.0"
scopeguard = "1.2.0"
unicode-xid = "0.2.6"
